# Сети и тома — объявляем заранее
# Все контейнеры будут в одной сети и смогут
# обращаться друг к другу по имени сервиса
networks:
  etl-network:
    driver: bridge

volumes:
  hadoop_namenode:    # постоянное хранилище метаданных HDFS
  hadoop_datanode:    # постоянное хранилище самих данных
  postgres_data:      # база данных Airflow
  airflow_logs:       # логи всех запусков DAG

# ─────────────────────────────────────────
# HDFS
# ─────────────────────────────────────────
services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    networks:
      - etl-network
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=etl-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
      - HDFS_CONF_dfs_permissions_enabled=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 30s
      timeout: 10s
      retries: 5

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    networks:
      - etl-network
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
      - HDFS_CONF_dfs_permissions_enabled=false
    depends_on:
      namenode:
        condition: service_healthy

# ─────────────────────────────────────────
# SPARK
# ─────────────────────────────────────────
  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    hostname: spark-master
    networks:
      - etl-network
    ports:
      - "8081:8080"
      - "7077:7077"
    environment:
      - SPARK_NO_DAEMONIZE=true
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    env_file:
      - .env

  spark-worker:
    image: apache/spark:3.5.3
    container_name: spark-worker
    hostname: spark-worker
    networks:
      - etl-network
    ports:
      - "8082:8081"
    environment:
      - SPARK_NO_DAEMONIZE=true
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    env_file:
      - .env
    depends_on:
      - spark-master
# ─────────────────────────────────────────
# AIRFLOW
# ─────────────────────────────────────────
  postgres:
    image: postgres:15
    container_name: airflow-postgres
    networks:
      - etl-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5

  airflow-init:
    image: apache/airflow:2.8.1
    container_name: airflow-init
    restart: "no"  # этот контейнер не перезапускается, он выполняет инициализацию и завершается
    networks:
      - etl-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    # Этот контейнер запускается ОДИН РАЗ — создаёт таблицы в БД
    # и создаёт admin пользователя, потом завершается
    command: >
      bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow-scheduler
    networks:
      - etl-network
    depends_on:
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags          # наши DAG-и
      - ./jobs:/opt/airflow/jobs          # наши PySpark jobs
      - airflow_logs:/opt/airflow/logs
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    command: scheduler

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow-webserver
    networks:
      - etl-network
    depends_on:
      - airflow-scheduler
    ports:
      - "8080:8080"   # Airflow UI — откроешь localhost:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./jobs:/opt/airflow/jobs
      - airflow_logs:/opt/airflow/logs
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    command: webserver